require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
use_frameworks!
target 'rnpush' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  target 'rnpushTests' do
    inherit! :complete
    # Pods for testing
  end
  
  post_install do |installer|
    react_native_post_install(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
      
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
    
    installer.pods_project.targets.each do |target|
        if ['RNFBApp', 'RNFBMessaging'].include?(target.name)
          target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
        elsif target.name.eql?('RNFBAnalytics')
          target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'FirebaseAnalytics'})
          target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleAppMeasurement'})
          target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'nanopb'})
          target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
        end
      end
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!({ 'Flipper' => '0.87.0' })
    
  # post_install do |installer|
  #   react_native_post_install(installer)
  #   flipper_post_install(installer)
  # end
end

target 'NotificationServiceExtension' do
  pod 'CTNotificationService'
  pod 'CleverTap-iOS-SDK'
end
